insert into Staff(last,first,salary,title) values ('Adams',' Ian H.',45000.00,'EXECUTIVE ASSISTANT ');
insert into Staff(last,first,salary,title) values ('Agnew',' David P.',93840.00,'DEPUTY DIRECTOR ');
insert into Staff(last,first,salary,title) values ('Albino',' James ',91800.00,'SENIOR PROGRAM MANAGER');
insert into Staff(last,first,salary,title) values ('Alley',' Hilary J.',42000.00,'STAFF ASSISTANT');
insert into Staff(last,first,salary,title) values ('Amorsingh',' Lucius L.',56092.00,'SPECIAL ASSISTANT');
insert into Staff(last,first,salary,title) values ('Anderson',' Amanda D.',60000.00,'SPECIAL ASSISTANT TO THE CHIEF OF STAFF');
insert into Staff(last,first,salary,title) values ('Anderson',' Charles D.',51000.00,'POLICY ASSISTANT');
insert into Staff(last,first,salary,title) values ('Andrias',' Kate E.',130500.00,'SPECIAL ASSISTANT ');
insert into Staff(last,first,salary,title) values ('Anello',' Russell M.',66300.00,'COUNSEL');
insert into Staff(last,first,salary,title) values ('Asen',' Jonathan D.',42000.00,'SENIOR ANALYST');
insert into Staff(last,first,salary,title) values ('Attili',' Candice L.',58511.00,'ASSISTANT SHIFT LEADER');
insert into Staff(last,first,salary,title) values ('Axelrod',' David M.',172200.00,'ASSISTANT TO THE PRESIDENT ');
insert into Staff(last,first,salary,title) values ('Ayling',' Lindsay A.',42000.00,'ANALYST');
insert into Staff(last,first,salary,title) values ('Baggetto',' Maude L.',42000.00,'STAFF ASSISTANT');
insert into Staff(last,first,salary,title) values ('Baldassaro',' Frederick J.',122744.00,'COMMUNICATIONS DIRECTOR');
insert into Staff(last,first,salary,title) values ('Barnes',' Melody C.',172200.00,'ASSISTANT TO THE PRESIDENT ');
insert into Staff(last,first,salary,title) values ('Bassin',' Ian M.',99000.00,'DEPUTY ASSOCIATE COUNSEL');
insert into Staff(last,first,salary,title) values ('Bates',' Andrew J.',42000.00,'MEDIA MONITOR');
insert into Staff(last,first,salary,title) values ('Bauer',' Nicholas T.',55000.00,'ASSOCIATE DIRECTOR');
insert into Staff(last,first,salary,title) values ('Bauer',' Robert F.',172200.00,'ASSISTANT TO THE PRESIDENT ');
insert into Staff(last,first,salary,title) values ('Becnel',' Bradley D.',55000.00,'SPECIAL ASSISTANT ');
insert into Staff(last,first,salary,title) values ('Bedingfield',' Katherine J.',90000.00,'DEPUTY DIRECTOR ');
insert into Staff(last,first,salary,title) values ('Beinart',' Diana H.',130500.00,'SPECIAL ASSISTANT ');
insert into Staff(last,first,salary,title) values ('Belive',' Lauren E.',45000.00,'LEGISLATIVE ASSISTANT ');
insert into Staff(last,first,salary,title) values ('Beliveau',' Emmett S.',130000.00,'DEPUTY ASSISTANT ');
insert into Staff(last,first,salary,title) values ('Bernard',' Sarah C.',70000.00,'DIRECTOR');
insert into Staff(last,first,salary,title) values ('Beverly',' Alaina C.',71400.00,'ASSOCIATE DIRECTOR ');
insert into Staff(last,first,salary,title) values ('Bhowmik',' Rachana',100000.00,'DIRECTOR ');
insert into Staff(last,first,salary,title) values ('Binns',' Mary U.',70126.00,'SPECIAL ASSISTANT');
insert into Staff(last,first,salary,title) values ('Birdsall',' Kristen S.',45900.00,'RESEARCHER');
insert into Staff(last,first,salary,title) values ('Bisi',' Rachel I.',42000.00,'LEGISLATIVE ASSISTANT');
insert into Staff(last,first,salary,title) values ('Blake',' Michael A.',61200.00,'DEPUTY ASSOCIATE DIRECTOR ');
insert into Staff(last,first,salary,title) values ('Block',' Michael R.',42000.00,'STAFF ASSISTANT');
insert into Staff(last,first,salary,title) values ('Blount',' Patricia H.',44402.00,'RECORDS MANAGEMENT ANALYST');
insert into Staff(last,first,salary,title) values ('Bond',' Brian K.',93840.00,'DEPUTY DIRECTOR OF PUBLIC ENGAGEMENT');
insert into Staff(last,first,salary,title) values ('Bookey-Baker',' Natalie F.',45000.00,'EXECUTIVE ASSISTANT ');
insert into Staff(last,first,salary,title) values ('Branch',' Katherine Y.',61200.00,'SPECIAL ASSISTANT ');
insert into Staff(last,first,salary,title) values ('Brennan',' John O.',172200.00,'ASSISTANT TO THE PRESIDENT ');
insert into Staff(last,first,salary,title) values ('Bressler',' Steven Y.',148510.00,'CLEARANCE ADVISOR');
insert into Staff(last,first,salary,title) values ('Brewer',' Anne P.',45000.00,'EXECUTIVE ASSISTANT ');
insert into Staff(last,first,salary,title) values ('Brooke',' Mary J.',89033.00,'SUPERVISOR ');
insert into Staff(last,first,salary,title) values ('Brown',' Elizabeth M.',172200.00,'ASSISTANT ');
insert into Staff(last,first,salary,title) values ('Browner',' Carol M.',172200.00,'ASSISTANT ');
insert into Staff(last,first,salary,title) values ('Brundage',' Amy J.',78000.00,'ASSISTANT PRESS SECRETARY');
insert into Staff(last,first,salary,title) values ('Brush',' Michael P.',56100.00,'SPECIAL ASSISTANT ');
insert into Staff(last,first,salary,title) values ('Buffett',' Howard W.',51630.00,'POLICY ADVISOR');
insert into Staff(last,first,salary,title) values ('Burman',' Kendall C.',130500.00,'SPECIAL ASSISTANT ');
insert into Staff(last,first,salary,title) values ('Burnough',' Erinn J.',66300.00,'DEPUTY DIRECTOR ');
insert into Staff(last,first,salary,title) values ('Burton',' William A.',113000.00,'SPECIAL ASSISTANT ');
insert into Staff(last,first,salary,title) values ('Campbell',' Frances L.',100904.00,'SUPERVISOR');
insert into Staff(last,first,salary,title) values ('Campbell',' Grant E.',45900.00,'ASSOCIATE DIRECTOR ');
insert into Staff(last,first,salary,title) values ('Campbell',' Nnaji-Semayi K.',42000.00,'SENIOR ANALYST');
insert into Staff(last,first,salary,title) values ('Campos',' David R.',42000.00,'ANALYST');
insert into Staff(last,first,salary,title) values ('Campoverdi',' Alejandra M.',60000.00,'SPECIAL ASSISTANT ');
insert into Staff(last,first,salary,title) values ('CamuÃ±ez',' Michael C.',140000.00,'SPECIAL ASSISTANT ');
insert into Staff(last,first,salary,title) values ('Canery',' Beverly D.',58511.00,'ASSISTANT SHIFT LEADER');
insert into Staff(last,first,salary,title) values ('Carden',' Meredith M.',42000.00,'STAFF ASSISTANT');
insert into Staff(last,first,salary,title) values ('Cardwell',' Rebecca A.',43656.00,'OPERATOR');
insert into Staff(last,first,salary,title) values ('Carrier',' Ethan A.',94969.00,'ETHICS ADVISOR');
insert into Staff(last,first,salary,title) values ('Carter',' Rhonda M.',57000.00,'SPECIAL ASSISTANT ');
insert into Staff(last,first,salary,title) values ('Castillo',' Laura M.',42000.00,'ANALYST');
insert into Staff(last,first,salary,title) values ('Chaifetz',' Samantha L.',123758.00,'RESEARCHER');
insert into Staff(last,first,salary,title) values ('Chambers',' Caroline M.',120000.00,'DIRECTOR OF CONFIRMATIONS');
insert into Staff(last,first,salary,title) values ('Chen',' Margaret C.',0.00,'SPECIAL ASSISTANT');
insert into Staff(last,first,salary,title) values ('Cherlin',' Reid H.',78000.00,'ASSISTANT PRESS SECRETARY');
insert into Staff(last,first,salary,title) values ('Chhabra',' Anand',42000.00,'STAFF ASSISTANT');
insert into Staff(last,first,salary,title) values ('Chiodo',' Theodore A.',60000.00,'ASSISTANT STAFF SECRETARY');
insert into Staff(last,first,salary,title) values ('Cizner',' Jennifer C.',85680.00,'DEPUTY CHIEF OF STAFF ');
insert into Staff(last,first,salary,title) values ('Clarke',' Kay F.',64439.00,'SHIFT LEADER');
insert into Staff(last,first,salary,title) values ('Claude',' Lilia H.',58511.00,'ASSISTANT SHIFT LEADER');
insert into Staff(last,first,salary,title) values ('Cobbina',' Kwesi A.',42000.00,'STAFF ASSISTANT');
insert into Staff(last,first,salary,title) values ('Cohen',' Elizabeth S',45900.00,'ASSOCIATE DIRECTOR ');
insert into Staff(last,first,salary,title) values ('Cokley',' Rebecca A.',72000.00,'PRIORITY PLACEMENT DIRECTOR');
insert into Staff(last,first,salary,title) values ('Colvin',' Nicholas M.',63240.00,'SPECIAL ASSISTANT ');
insert into Staff(last,first,salary,title) values ('Conrad',' Shasti K. ',42000.00,'STAFF ASSISTANT');
insert into Staff(last,first,salary,title) values ('Corrigan',' Tara C.',45000.00,'EXECUTIVE ASSISTANT ');
insert into Staff(last,first,salary,title) values ('Coven',' Martha B.',120000.00,'SPECIAL ASSISTANT ');
insert into Staff(last,first,salary,title) values ('Crowley',' Jeffrey S.',102000.00,'DIRECTOR ');
insert into Staff(last,first,salary,title) values ('Crutchfield',' Danielle M.',130000.00,'DEPUTY ASSISTANT ');
insert into Staff(last,first,salary,title) values ('Cuba',' Juan C.',42000.00,'STAFF ASSISTANT');
insert into Staff(last,first,salary,title) values ('Cuellar',' Martin E.',91800.00,'DEPUTY DIRECTOR');
insert into Staff(last,first,salary,title) values ('Cunningham',' Jason F.',64548.00,'RESEARCHER');
insert into Staff(last,first,salary,title) values ('Cunningham',' Vinson T.',42000.00,'ECONOMICS STAFF ASSISTANT');
insert into Staff(last,first,salary,title) values ('Cusack',' David J.',102000.00,'SPECIAL ASSISTANT ');
insert into Staff(last,first,salary,title) values ('Cushman',' Chase M.',45900.00,'ASSOCIATE DIRECTOR OF SCHEDULING');
insert into Staff(last,first,salary,title) values ('Cutter',' Stephanie ',172200.00,'ASSISTANT TO THE PRESIDENT ');
insert into Staff(last,first,salary,title) values ('Dale',' Kareem A.',61200.00,'SPECIAL ASSISTANT ');
insert into Staff(last,first,salary,title) values ('Dalheim',' Karen L.',148510.00,'ETHICS ADVISOR');
insert into Staff(last,first,salary,title) values ('Davies',' Susan M.',158500.00,'DEPUTY ASSISTANT ');
insert into Staff(last,first,salary,title) values ('Davis',' Christopher E.',76500.00,'SENIOR ANALYST');
insert into Staff(last,first,salary,title) values ('Deese',' Brian C.',130500.00,'SPECIAL ASSISTANT ');
insert into Staff(last,first,salary,title) values ('DeGuzman',' Brian K.',42738.00,'OPERATOR');
insert into Staff(last,first,salary,title) values ('DeParle',' Nancy-Ann Min',158500.00,'COUNSELOR ');
insert into Staff(last,first,salary,title) values ('DeRosa',' Mary B.',158500.00,'DEPUTY ASSISTANT');
insert into Staff(last,first,salary,title) values ('Devine',' Carrie S.',56100.00,'SPECIAL ASSISTANT ');
insert into Staff(last,first,salary,title) values ('Dillon',' Michael P.',113000.00,'SPECIAL ASSISTANT ');
insert into Staff(last,first,salary,title) values ('Donilon',' Thomas E.',172200.00,'ASSISTANT TO THE PRESIDENT');
insert into Staff(last,first,salary,title) values ('Donovan',' Michael W.',45900.00,'ASSOCIATE DIRECTOR ');
insert into Staff(last,first,salary,title) values ('Donovan',' William J.',42000.00,'STAFF ASSISTANT');
insert into Staff(last,first,salary,title) values ('Dorsett',' Craig M.',42000.00,'ANALYST');
insert into Staff(last,first,salary,title) values ('Douglas',' Derek R. B.',120000.00,'SPECIAL ASSISTANT ');
insert into Staff(last,first,salary,title) values ('Droege',' Philip C.',140259.00,'DIRECTOR OF RECORDS MANAGEMENT');
insert into Staff(last,first,salary,title) values ('DuBois',' Joshua P.',100000.00,'SPECIAL ASSISTANT ');
insert into Staff(last,first,salary,title) values ('Dunn',' Lauren P.',50000.00,'POLICY ASSISTANT');
insert into Staff(last,first,salary,title) values ('Dyer',' Deesha A.',45000.00,'ASSOCIATE DIRECTOR ');
insert into Staff(last,first,salary,title) values ('Ealons',' Corey A.',79560.00,'DIRECTOR ');
insert into Staff(last,first,salary,title) values ('Earnest',' Joshua R.',113000.00,'SPECIAL ASSISTANT ');
insert into Staff(last,first,salary,title) values ('Edgerton',' Erin M.',89033.00,'NEW MEDIA ANALYST');
insert into Staff(last,first,salary,title) values ('Edmonds',' Anita J.',49069.00,'RECORDS MANAGEMENT ANALYST');
insert into Staff(last,first,salary,title) values ('Edwards',' Lisa W.',155500.00,'DEPUTY ASSOCIATE ');
insert into Staff(last,first,salary,title) values ('Eisen',' Norman L.',149000.00,'SPECIAL ASSISTANT ');
insert into Staff(last,first,salary,title) values ('Emanuel',' Rahm I.',172200.00,'ASSISTANT TO THE PRESIDENT ');
insert into Staff(last,first,salary,title) values ('Escobar',' Felicia A. ',90000.00,'SENIOR POLICY ADVISOR');
insert into Staff(last,first,salary,title) values ('Espinel',' Zulima L.',130500.00,'SPECIAL ASSISTANT ');
insert into Staff(last,first,salary,title) values ('Farrell',' Diana',147500.00,'DEPUTY ASSISTANT ');
insert into Staff(last,first,salary,title) values ('Faulman',' Michael T.',42000.00,'ADVANCE COORDINATOR');
insert into Staff(last,first,salary,title) values ('Favreau',' Jonathan E.',172200.00,'ASSISTANT TO THE PRESIDENT ');
insert into Staff(last,first,salary,title) values ('Fenn',' Sarah B.',42000.00,'STAFF ASSISTANT');
insert into Staff(last,first,salary,title) values ('Fergenson',' Micah F.',42000.00,'STAFF ASSISTANT');
insert into Staff(last,first,salary,title) values ('Fernandez',' Micaela J.',102000.00,'SPECIAL ASSISTANT');
insert into Staff(last,first,salary,title) values ('Fernkas',' Robin E.',126251.00,'POLICY ADVISOR');
insert into Staff(last,first,salary,title) values ('Finkenbinder',' Benjamin N.',45900.00,'ASSOCIATE DIRECTOR ');
insert into Staff(last,first,salary,title) values ('Finlen',' Shawn T.',50000.00,'ASSISTANT DIRECTOR');
insert into Staff(last,first,salary,title) values ('Firestone',' Daren H.',105211.00,'DEPUTY ASSOCIATE');
insert into Staff(last,first,salary,title) values ('Fiscus',' Taylor R.',45000.00,'ASSOCIATE DIRECTOR');
insert into Staff(last,first,salary,title) values ('Fitts',' Alan 0.',61200.00,'DEPUTY DIRECTOR ');
insert into Staff(last,first,salary,title) values ('Flatgard',' Benjamin W.',55000.00,'ECONOMICS DIRECTOR');
insert into Staff(last,first,salary,title) values ('Ford',' Harrison A.',42000.00,'SENIOR ANALYST');
insert into Staff(last,first,salary,title) values ('Frank',' April P.',42000.00,'STAFF ASSISTANT');
insert into Staff(last,first,salary,title) values ('Frankel',' Adam P.',100000.00,'SPECIAL ASSISTANT ');
insert into Staff(last,first,salary,title) values ('Freeman',' Myra B.',73917.00,'MANAGEMENT ANALYST');
insert into Staff(last,first,salary,title) values ('Frye',' Jocelyn C.',140000.00,'DEPUTY ASSISTANT ');
insert into Staff(last,first,salary,title) values ('Furman',' Jason L.',147500.00,'DEPUTY ASSISTANT ');
insert into Staff(last,first,salary,title) values ('Gage',' Peter T.',94969.00,'POLICY ANALYST');
insert into Staff(last,first,salary,title) values ('Garcia',' Kristin M.',45000.00,'LEGISLATIVE ASSISTANT ');
insert into Staff(last,first,salary,title) values ('Gardaphe',' Frederico C.',50000.00,'ASSISTANT DIRECTOR');
insert into Staff(last,first,salary,title) values ('Gaspard',' Patrick H.',172200.00,'ASSISTANT TO THE PRESIDENT');
insert into Staff(last,first,salary,title) values ('Gibbs',' Robert L.',172200.00,'ASSISTANT TO THE PRESIDENT ');
insert into Staff(last,first,salary,title) values ('Gillette',' Jodi A.',71400.00,'DEPUTY ASSOCIATE DIRECTOR ');
insert into Staff(last,first,salary,title) values ('Godfrey',' Harrison T.',42000.00,'LEGISLATIVE ASSISTANT');
insert into Staff(last,first,salary,title) values ('Gomez',' David F.',45000.00,'RESEARCHER');
insert into Staff(last,first,salary,title) values ('Gonzalez',' Roberto J.',114000.00,'SPECIAL ASSISTANT ');
insert into Staff(last,first,salary,title) values ('Goodman',' Jennifer',63240.00,'DEPUTY DIRECTOR');
insert into Staff(last,first,salary,title) values ('Goodman',' Mary B.',130500.00,'SPECIAL ASSISTANT ');
insert into Staff(last,first,salary,title) values ('Gottlieb',' Graham D.',42000.00,' STAFF ASSISTANT');
insert into Staff(last,first,salary,title) values ('Gottlieb',' Michael J.',114000.00,'SPECIAL ASSISTANT ');
insert into Staff(last,first,salary,title) values ('Gottry',' Heather C.',136134.00,'ASSOCIATE COUNSEL ');
insert into Staff(last,first,salary,title) values ('Graham',' Lottie B.',63673.00,'ASSISTANT SHIFT LEADER');
insert into Staff(last,first,salary,title) values ('Grant',' Kathryn A.',42000.00,'ANALYST');
insert into Staff(last,first,salary,title) values ('Gray',' Danielle C.',130500.00,'SPECIAL ASSISTANT ');
insert into Staff(last,first,salary,title) values ('Green',' Jason G.',99000.00,'DEPUTY ASSOCIATE COUNSEL');
insert into Staff(last,first,salary,title) values ('Green',' Valerie E.',113000.00,'SPECIAL ASSISTANT ');
insert into Staff(last,first,salary,title) values ('Greenawalt',' Andrei M.',80000.00,'DEPUTY DIRECTOR');
insert into Staff(last,first,salary,title) values ('Greene',' Norman A.',66300.00,'DEPUTY DIRECTOR OF FINANCE');
insert into Staff(last,first,salary,title) values ('Groth',' Travis R.',42840.00,'STAFF ASSISTANT');
insert into Staff(last,first,salary,title) values ('Hable',' Abigail K.',45000.00,'EXECUTIVE ASSISTANT');
insert into Staff(last,first,salary,title) values ('Hanson',' Terry P.',42000.00,'DOMESTIC STAFF ASSISTANT');
insert into Staff(last,first,salary,title) values ('Harper',' Ryan M.',56100.00,'DOMESTIC DIRECTOR');
insert into Staff(last,first,salary,title) values ('Harris',' Kimberley D.',130500.00,'SPECIAL ASSISTANT ');
insert into Staff(last,first,salary,title) values ('Harris',' Kevin R.',42000.00,'LEGISLATIVE ASSISTANT');
insert into Staff(last,first,salary,title) values ('Hash',' Michael M.',179700.00,'DEPUTY DIRECTOR');
insert into Staff(last,first,salary,title) values ('Hegde',' Shilpa S.',42000.00,'ANALYST');
insert into Staff(last,first,salary,title) values ('Heimbach',' James T.',130500.00,'SPECIAL ASSISTANT ');
insert into Staff(last,first,salary,title) values ('Hennigan',' Margo E.',45900.00,'ASSOCIATE DIRECTOR ');
insert into Staff(last,first,salary,title) values ('Hernandez',' Philip M.',42000.00,'STAFF ASSISTANT');
insert into Staff(last,first,salary,title) values ('Hiatt',' Natalie M.',42000.00,'OPERATOR');
insert into Staff(last,first,salary,title) values ('Higginbottom',' Heather A.',150000.00,'DEPUTY ASSISTANT ');
insert into Staff(last,first,salary,title) values ('Hitchcock',' Adam S.',51000.00,'SPECIAL ASSISTANT');
insert into Staff(last,first,salary,title) values ('Hoang',' Vy T.',44402.00,'RECORDS MANAGEMENT ANALYST');
insert into Staff(last,first,salary,title) values ('Hogan',' Katherine J.',45900.00,'ASSOCIATE DIRECTOR');
insert into Staff(last,first,salary,title) values ('Hogan',' Nancy D.',145000.00,'DEPUTY ASSISTANT');
insert into Staff(last,first,salary,title) values ('Hopkins',' Marissa C.',60000.00,'SPECIAL ASSISTANT');
insert into Staff(last,first,salary,title) values ('Hornsby',' Michael A.',66300.00,'ASSISTANT DIRECTOR');
insert into Staff(last,first,salary,title) values ('Hughes',' Caroline E.',42000.00,'PRESS ASSISTANT');
insert into Staff(last,first,salary,title) values ('Hurley',' Caitlin G.',60000.00,'ASSISTANT STAFF SECRETARY');
insert into Staff(last,first,salary,title) values ('Hurwitz',' Sarah K.',100000.00,'SPECIAL ASSISTANT ');
insert into Staff(last,first,salary,title) values ('Inouye',' Shinichi',78000.00,'DIRECTOR OF SPECIALITY MEDIA');
insert into Staff(last,first,salary,title) values ('Jabbour',' Mona K.',80000.00,'DEPUTY ASSOCIATE COUNSEL ');
insert into Staff(last,first,salary,title) values ('Jackson',' Deilia A. L.',42000.00,'DEPUTY ASSOCIATE DIRECTOR ');
insert into Staff(last,first,salary,title) values ('Jackson',' Elizabeth J.',37983.00,'RECORDS MANAGEMENT ANALYST');
insert into Staff(last,first,salary,title) values ('Jackson',' Theresa R.',64439.00,'SHIFT LEADER');
insert into Staff(last,first,salary,title) values ('Jamison',' Linda S.',113000.00,'SPECIAL ASSISTANT ');
insert into Staff(last,first,salary,title) values ('Jarrett',' Valerie B.',172200.00,'SENIOR ADVISOR AND ASSISTANT ');
insert into Staff(last,first,salary,title) values ('Jarvis',' Kristen E.',51000.00,'SPECIAL ASSISTANT');
insert into Staff(last,first,salary,title) values ('Jarvis-Shean',' Elizabeth P.',100000.00,'SPECIAL ASSISTANT ');
insert into Staff(last,first,salary,title) values ('Jawando',' William O.',89033.00,'DEPUTY ASSOCIATE DIRECTOR');
insert into Staff(last,first,salary,title) values ('Jean-Pierre',' Karine',76500.00,'NORTHEAST POLITICAL DIRECTOR');
insert into Staff(last,first,salary,title) values ('Johnson',' Katherine B.',90000.00,'PERSONAL AIDE TO THE PRESIDENT');
insert into Staff(last,first,salary,title) values ('Johnson',' Linda M.',66335.00,'SHIFT LEADER');
insert into Staff(last,first,salary,title) values ('Johnston',' Camille Y.',102000.00,'SPECIAL ASSISTANT ');
insert into Staff(last,first,salary,title) values ('Jones',' Crystal B.',84855.00,'ASSISTANT SUPERVISOR');
insert into Staff(last,first,salary,title) values ('Jones',' Elizabeth A.',100000.00,'DIRECTOR OF WHITE HOUSE ADMINISTRATION');
insert into Staff(last,first,salary,title) values ('Jones',' James L.',172200.00,'NATIONAL SECURITY ADVISOR');
insert into Staff(last,first,salary,title) values ('Jones',' Kristin T.',42000.00,'RESEARCH ASSOCIATE');
insert into Staff(last,first,salary,title) values ('Jung',' Bryan',50000.00,'SPECIAL ASSISTANT TO THE DIRECTOR');
insert into Staff(last,first,salary,title) values ('Juska',' Monika',45000.00,'ASSOCIATE DIRECTOR');
insert into Staff(last,first,salary,title) values ('Kalbaugh',' David E.',129758.00,'DEPUTY EXECUTIVE CLERK');
insert into Staff(last,first,salary,title) values ('Kale',' Katy A.',130500.00,'SPECIAL ASSISTANT ');
insert into Staff(last,first,salary,title) values ('Kammerer',' Chelsea J.',56100.00,'SPECIAL ASSISTANT');
insert into Staff(last,first,salary,title) values ('Kang',' Christopher D.',130500.00,'SPECIAL ASSISTANT ');
insert into Staff(last,first,salary,title) values ('Kang',' Eugene J.',48095.00,'SPECIAL PROJECTS COORDINATOR');
insert into Staff(last,first,salary,title) values ('Keenan',' Cody S.',75000.00,'PRESIDENTIAL SPEECHWRITER');
insert into Staff(last,first,salary,title) values ('Kelly',' Allison K.',45000.00,'VETTER');
insert into Staff(last,first,salary,title) values ('Kennedy',' Joseph B.',42000.00,'STAFF ASSISTANT');
insert into Staff(last,first,salary,title) values ('Kennedy',' Sean D.',130500.00,'SPECIAL ASSISTANT ');
insert into Staff(last,first,salary,title) values ('Kiley',' Bradley J.',162900.00,'ASSISTANT');
insert into Staff(last,first,salary,title) values ('Kim',' Anna S.',60000.00,'ASSISTANT STAFF SECRETARY');
insert into Staff(last,first,salary,title) values ('Kimball',' Astri B.',85000.00,'DEPUTY DIRECTOR ');
insert into Staff(last,first,salary,title) values ('King',' Taeshonnda C.',60232.00,'RECORDS MANAGEMENT ANALYST');
insert into Staff(last,first,salary,title) values ('Kocher',' Robert P.',130500.00,'SPECIAL ASSISTANT ');
insert into Staff(last,first,salary,title) values ('Kochman',' Katherine H.',45000.00,'SCHEDULER FOR CHIEF OF STAFF');
insert into Staff(last,first,salary,title) values ('Kohnke',' Lisa J.',60000.00,'DEPUTY DIRECTOR ');
insert into Staff(last,first,salary,title) values ('Kommareddi',' Madhuri',71400.00,'ASSOCIATE STAFF SECRETARY');
insert into Staff(last,first,salary,title) values ('Konwinski',' Lisa M.',158500.00,'DEPUTY ASSISTANT ');
insert into Staff(last,first,salary,title) values ('Koo',' Stacy J.',55000.00,'DEPUTY ASSOCIATE DIRECTOR');
insert into Staff(last,first,salary,title) values ('Kramer',' Douglas J.',155500.00,'DEPUTY ASSOCIATE COUNSEL ');
insert into Staff(last,first,salary,title) values ('Krass',' Caroline D.',130500.00,'SPECIAL ASSISTANT TO THE PRESIDENT ');
insert into Staff(last,first,salary,title) values ('Kravis',' Jonathan I.',130500.00,'SPECIAL ASSISTANT TO THE PRESIDENT T');
insert into Staff(last,first,salary,title) values ('Kumar',' Pravin D.',50000.00,'ASSISTANT COUNSEL');
insert into Staff(last,first,salary,title) values ('LaBolt',' Benjamin C.',78000.00,'ASSISTANT PRESS SECRETARY');
insert into Staff(last,first,salary,title) values ('Lartey',' Solomon D.',56092.00,'RECORDS MANAGEMENT ANALYST');
insert into Staff(last,first,salary,title) values ('Larus',' Anne K.',56100.00,'DEPUTY DIRECTOR');
insert into Staff(last,first,salary,title) values ('Lechtenberg',' Tyler A',50000.00,'DIRECTOR OF CORRESPONDENCE ');
insert into Staff(last,first,salary,title) values ('Ledbetter',' Howli J.',42000.00,'COORDINATOR');
insert into Staff(last,first,salary,title) values ('Lee',' Gary S.',42000.00,'LEGISLATIVE ASSISTANT');
insert into Staff(last,first,salary,title) values ('Lee',' Jesse C.',71400.00,'DIRECTOR OF ONLINE PROGRAMS');
insert into Staff(last,first,salary,title) values ('Leger',' Daniella G.',102000.00,'SPECIAL ASSISTANT ');
insert into Staff(last,first,salary,title) values ('Lehrich',' Matthew A.',65000.00,'REGIONAL COMMUNICATIONS DIRECTOR');
insert into Staff(last,first,salary,title) values ('Leitner-Laserna',' Sofia I.',21000.00,'STAFF ASSISTANT');
insert into Staff(last,first,salary,title) values ('Lelyveld',' Catherine M.',85680.00,'DIRECTOR AND PRESS SECRETARY');
insert into Staff(last,first,salary,title) values ('Lepow',' Brandon D.',55000.00,'SPECIAL ASSISTANT AND PRESS LEAD');
insert into Staff(last,first,salary,title) values ('Lerner',' Jeffrey B. W.',76500.00,'SOUTHERN POLITICAL DIRECTOR');
insert into Staff(last,first,salary,title) values ('Lesser',' Eric P.',60000.00,'SPECIAL ASSISTANT TO THE SENIOR ADVISOR');
insert into Staff(last,first,salary,title) values ('Levine',' Jacob C.',45000.00,'POLICY ANALYST');
insert into Staff(last,first,salary,title) values ('Levine',' Marne L.',130500.00,'SPECIAL ASSISTANT ');
insert into Staff(last,first,salary,title) values ('Lewin',' Jesse M.',42000.00,'PRESS ASSISTANT');
insert into Staff(last,first,salary,title) values ('Lewis',' Dana M.',66000.00,'SPECIAL ASSISTANT ');
insert into Staff(last,first,salary,title) values ('Lewis',' Georgette T.',45000.00,'COORDINATOR');
insert into Staff(last,first,salary,title) values ('Lewis',' Kevin S.',42000.00,'PRESS ASSISTANT');
insert into Staff(last,first,salary,title) values ('Lezotte',' Darin R.',62544.00,'RECORDS MANAGEMENT ANALYST');
insert into Staff(last,first,salary,title) values ('Liddell-Westefeld',' Christopher',50000.00,'ASSISTANT DIRECTOR');
insert into Staff(last,first,salary,title) values ('Liegel',' Christopher J.',37826.00,'RECORDS MANAGEMENT ANALYST');
insert into Staff(last,first,salary,title) values ('Lillie',' Catherine E.',70000.00,'DIRECTOR OF PRESS ADVANCE');
insert into Staff(last,first,salary,title) values ('Limon',' Noerena',42000.00,'STAFF ASSISTANT');
insert into Staff(last,first,salary,title) values ('Lippert',' Mark W.',147500.00,'DEPUTY ASSISTANT ');
insert into Staff(last,first,salary,title) values ('Lipsky',' Joshua S.',45000.00,'ASSOCIATE DIRECTOR');
insert into Staff(last,first,salary,title) values ('Lipton',' David A.',149000.00,'SPECIAL ASSISTANT ');
insert into Staff(last,first,salary,title) values ('Loeb',' Emily M.',60000.00,'LEGISLATIVE COUNSEL ');
insert into Staff(last,first,salary,title) values ('London',' Seth A.',45000.00,'LEGISLATIVE ASSISTANT');
insert into Staff(last,first,salary,title) values ('Lorjuste',' Gregory',45900.00,'ASSOCIATE DIRECTOR');
insert into Staff(last,first,salary,title) values ('Love',' Reginald L.',102000.00,'SPECIAL ASSISTANT');
insert into Staff(last,first,salary,title) values ('Love',' Timothy P.',179700.00,'POLICY DIRECTOR');
insert into Staff(last,first,salary,title) values ('Lovett',' Jonathan I.',75000.00,'PRESIDENTIAL SPEECHWRITER');
insert into Staff(last,first,salary,title) values ('Lu',' Christopher P.',172200.00,'ASSISTANT TO THE PRESIDENT ');
insert into Staff(last,first,salary,title) values ('Luck',' Deatrice N.',43860.00,'SPECIAL SERVICES OPERATOR');
insert into Staff(last,first,salary,title) values ('Lynn',' Anthony V.',45000.00,'COORDINATOR');
insert into Staff(last,first,salary,title) values ('Mack',' William B.',80000.00,'DEPUTY ASSOCIATE COUNSEL');
insert into Staff(last,first,salary,title) values ('Mackey',' Erin E.',66300.00,'DIRECTOR OF FINANCE');
insert into Staff(last,first,salary,title) values ('Maher',' Shawn P.',158500.00,'DEPUTY ASSISTANT');
insert into Staff(last,first,salary,title) values ('Markovitz',' Alison J.',80000.00,'DEPUTY ASSOCIATE COUNSEL ');
insert into Staff(last,first,salary,title) values ('Martin',' Joanna G.',102000.00,'SPECIAL ASSISTANT ');
insert into Staff(last,first,salary,title) values ('Maska',' Johanna M.',56100.00,'SPECIAL ASSISTANT');
insert into Staff(last,first,salary,title) values ('Massey',' Katherine',165000.00,'SENIOR POLICY DIRECTOR');
insert into Staff(last,first,salary,title) values ('Mastromonaco',' Alyssa M.',172200.00,'ASSISTANT TO THE PRESIDENT ');
insert into Staff(last,first,salary,title) values ('Mattson',' Philip C.',60232.00,'SPECIAL ASSISTANT');
insert into Staff(last,first,salary,title) values ('Mayekar',' Samir S.',56100.00,'NATIONAL SECURITY DIRECTOR');
insert into Staff(last,first,salary,title) values ('McBride',' Jonathan D.',130000.00,'SPECIAL ASSISTANT ');
insert into Staff(last,first,salary,title) values ('McCarthy',' Mary N.',155500.00,'POLICY ADVISOR');
insert into Staff(last,first,salary,title) values ('McCathran',' William W.',106839.00,'ASSISTANT EXECUTIVE CLERK');
insert into Staff(last,first,salary,title) values ('McDonough',' Denis R.',147500.00,'DEPUTY ASSISTANT');
insert into Staff(last,first,salary,title) values ('McGinnis',' Patricia G.',0.00,'ADVISOR');
insert into Staff(last,first,salary,title) values ('McGrath',' Shaun L.',93840.00,'DEPUTY DIRECTOR ');
insert into Staff(last,first,salary,title) values ('McGuire',' MaryEllen C.',91800.00,'SENIOR POLICY ADVISOR');
insert into Staff(last,first,salary,title) values ('McLaughlin',' Margaret T.',120000.00,'SPECIAL ASSISTANT');
insert into Staff(last,first,salary,title) values ('McNeal',' Melissa K.',51000.00,'DIRECTOR ');
insert into Staff(last,first,salary,title) values ('Mehrbani',' Rodin A.',80000.00,'DEPUTY ASSOCIATE COUNSEL');
insert into Staff(last,first,salary,title) values ('Messina',' James A.',172200.00,'ASSISTANT TO THE PRESIDENT ');
insert into Staff(last,first,salary,title) values ('Metcalf',' Ryan D.',42000.00,'ANALYST');
insert into Staff(last,first,salary,title) values ('Milakofsky',' Benjamin E.',45000.00,'SPECIAL ASSISTANT ');
insert into Staff(last,first,salary,title) values ('Millett',' Gregorio A.',115731.00,'SENIOR POLICY ADVISOR');
insert into Staff(last,first,salary,title) values ('Millison',' Chad L.',60232.00,'RECORDS MANAGEMENT ANALYST');
insert into Staff(last,first,salary,title) values ('Miranda',' Luis A.',78000.00,'DIRECTOR OF HISPANIC MEDIA');
insert into Staff(last,first,salary,title) values ('Moilanen',' Stephen S.',45000.00,'POLICY ANALYST');
insert into Staff(last,first,salary,title) values ('Monteiro',' Darron P.',61200.00,'DEPUTY ASSOCIATE DIRECTOR ');
insert into Staff(last,first,salary,title) values ('Mosteller',' Brian D.',90000.00,'PERSONAL AIDE TO THE PRESIDENT');
insert into Staff(last,first,salary,title) values ('Mrazek',' Susannah R.',42000.00,'SENIOR ANALYST');
insert into Staff(last,first,salary,title) values ('Mueller',' Lindsay E.',66300.00,'DIRECTOR OF OPERATIONS');
insert into Staff(last,first,salary,title) values ('MuÃ±oz',' Cecilia',153500.00,'DEPUTY ASSISTANT');
insert into Staff(last,first,salary,title) values ('Muntz',' Moira K. M.',66300.00,'DIRECTOR');
insert into Staff(last,first,salary,title) values ('Murtha',' Katherine R.',50000.00,'SENIOR VETTER');
insert into Staff(last,first,salary,title) values ('Nabors',' Robert L.',162500.00,'DEPUTY ASSISTANT ');
insert into Staff(last,first,salary,title) values ('Naidoff',' Caitlin L.',50000.00,'EXECUTIVE ASSISTANT ');
insert into Staff(last,first,salary,title) values ('Narechania',' Saumya N.',50000.00,'ASSISTANT DIRECTOR');
insert into Staff(last,first,salary,title) values ('Nathan',' Alison J.',130500.00,'SPECIAL ASSISTANT ');
insert into Staff(last,first,salary,title) values ('Neiman',' Wanda M.',74958.00,'ASSISTANT');
insert into Staff(last,first,salary,title) values ('Nelson',' Elizabeth W.',45900.00,'ASSOCIATE DIRECTOR ');
insert into Staff(last,first,salary,title) values ('Neralla',' Venkateswar N.',75480.00,'DIRECTOR');
insert into Staff(last,first,salary,title) values ('Newell',' Peter J.',71400.00,'DIRECTOR OF TRAVEL OFFICE');
insert into Staff(last,first,salary,title) values ('Nguyen',' Alexander T. H.',102829.00,'ETHICS ADVISOR');
insert into Staff(last,first,salary,title) values ('Noel',' Pascal J.',59160.00,'SENIOR POLICY ADVISOR');
insert into Staff(last,first,salary,title) values ('Northern',' Mary G.',42000.00,'STAFF ASSISTANT');
insert into Staff(last,first,salary,title) values ('Ocampo',' Maria L.',42000.00,'LEGISLATIVE ASSISTANT');
insert into Staff(last,first,salary,title) values ('Odintz',' Joshua D.',155500.00,'CHIEF TAX COUNSEL');
insert into Staff(last,first,salary,title) values ('Odio',' Carlos P.',56100.00,'DEPUTY ASSOCIATE DIRECTOR');
insert into Staff(last,first,salary,title) values ('Offerman',' Mary F.',45000.00,'DEPUTY ASSOCIATE DIRECTOR');
insert into Staff(last,first,salary,title) values ('Oleske',' James M.',114000.00,'CHIEF OF STAFF');
insert into Staff(last,first,salary,title) values ('Olmos',' Margaret C.',65000.00,'DEPUTY DIRECTOR');
insert into Staff(last,first,salary,title) values ('Olson',' Elizabeth H.',76500.00,'DEPUTY DIRECTOR');
insert into Staff(last,first,salary,title) values ('Onek',' Matthew M.',110000.00,'SPECIAL ASSISTANT');
insert into Staff(last,first,salary,title) values ('Ortiz',' Michael R.',45000.00,'LEGISLATIVE ASSISTANT ');
insert into Staff(last,first,salary,title) values ('Oxtoby',' John T.',42000.00,'SPECIAL ASSISTANT ');
insert into Staff(last,first,salary,title) values ('Page',' Darienne M.',42000.00,'WEST WING RECEPTIONIST');
insert into Staff(last,first,salary,title) values ('Paige',' Lauren R.',62000.00,'DIRECTOR ');
insert into Staff(last,first,salary,title) values ('Papa',' Gregory J.',130500.00,'SPECIAL ASSISTANT ');
insert into Staff(last,first,salary,title) values ('Papas',' Nicholas W.',92001.00,'DIRECTOR ');
insert into Staff(last,first,salary,title) values ('Parker',' Doris D.',79864.00,'ASSISTANT SUPERVISOR ');
insert into Staff(last,first,salary,title) values ('Pate',' Brian E.',46745.00,'PRESIDENTIAL SUPPORT SPECIALIST');
insert into Staff(last,first,salary,title) values ('Paulsen',' Joseph B.',56100.00,'DEPUTY DIRECTOR ');
insert into Staff(last,first,salary,title) values ('Perez',' Alejandro',130500.00,'SPECIAL ASSISTANT');
insert into Staff(last,first,salary,title) values ('Pfeiffer',' Howard D.',172200.00,'ASSISTANT ');
insert into Staff(last,first,salary,title) values ('Phadke',' Shilpa',80000.00,'DEPUTY DIRECTOR ');
insert into Staff(last,first,salary,title) values ('Pipkins',' Desiree E.',50000.00,'RESEARCH ASSISTANT');
insert into Staff(last,first,salary,title) values ('Pojman',' Natalie R.',45900.00,'EXECUTIVE ASSISTANT');
insert into Staff(last,first,salary,title) values ('Pope',' David F.',51000.00,'POLICY ASSISTANT');
insert into Staff(last,first,salary,title) values ('Pope',' Jamal A.',42000.00,'STAFF ASSISTANT');
insert into Staff(last,first,salary,title) values ('Portilla',' Zachary A.',42000.00,' STAFF ASSISTANT');
insert into Staff(last,first,salary,title) values ('Posey',' Stacie M.',42000.00,'ANALYST');
insert into Staff(last,first,salary,title) values ('Pourmorad',' Araz ',45000.00,'ASSOCIATE DIRECTOR');
insert into Staff(last,first,salary,title) values ('Psaki',' Jennifer R.',150000.00,'DEPUTY ASSISTANT ');
insert into Staff(last,first,salary,title) values ('Pulliam',' Allison C.',42000.00,'STAFF ASSISTANT');
insert into Staff(last,first,salary,title) values ('Quinn',' Brian P.',45000.00,'ASSOCIATE DIRECTOR');
insert into Staff(last,first,salary,title) values ('Raizk',' Paul S.',113605.00,'DEPUTY DIRECTOR');
insert into Staff(last,first,salary,title) values ('Rathod',' Nicholas S.',71400.00,'DEPUTY ASSOCIATE DIRECTOR');
insert into Staff(last,first,salary,title) values ('Reed',' Ian P.',45900.00,'ASSOCIATE DIRECTOR');
insert into Staff(last,first,salary,title) values ('Reeves',' Fiona O.',51000.00,'SENIOR WRITER');
insert into Staff(last,first,salary,title) values ('Reinstein',' Joseph B.',66300.00,'DEPUTY DIRECTOR ');
insert into Staff(last,first,salary,title) values ('Richardson',' Karen E.',92001.00,'ASSOCIATE DIRECTOR');
insert into Staff(last,first,salary,title) values ('Rittner',' Kathleen A.',144868.00,'ETHICS ADVISOR');
insert into Staff(last,first,salary,title) values ('Rivadeneira',' Shirley C.',55000.00,'ENERGY TDIRECTOR');
insert into Staff(last,first,salary,title) values ('Roach',' Cynthia L.',100904.00,'SUPERVISOR ');
insert into Staff(last,first,salary,title) values ('Roberts',' Blake C.',99000.00,'DEPUTY ASSOCIATE COUNSEL');
insert into Staff(last,first,salary,title) values ('Robertson',' Ian T.',42000.00,'ANALYST');
insert into Staff(last,first,salary,title) values ('Roche',' Mary K.',60000.00,'SPEECHWRITER');
insert into Staff(last,first,salary,title) values ('Roddick',' Gertrude A.',89846.00,'SPECIAL ASSISTANT');
insert into Staff(last,first,salary,title) values ('Rodriguez',' Roberto J.',120000.00,'SPECIAL ASSISTANT TO THE PRESIDENT ');
insert into Staff(last,first,salary,title) values ('Rosalsky',' Gregory E.',45000.00,'VETTER');
insert into Staff(last,first,salary,title) values ('Rouse',' Peter M.',172200.00,'ASSISTANT TO THE PRESIDENT ');
insert into Staff(last,first,salary,title) values ('Ruemmler',' Kathryn H.',158500.00,'DEPUTY ASSISTANT');
insert into Staff(last,first,salary,title) values ('Ruemmler',' Michael L.',56100.00,'SPECIAL ASSISTANT AND ADVANCE LEAD');
insert into Staff(last,first,salary,title) values ('Rundlet',' Peter F.',158500.00,'DEPUTY ASSISTANT ');
insert into Staff(last,first,salary,title) values ('Ryan',' Timothy J.',71400.00,'DIRECTOR OF TECHNOLOGY');
insert into Staff(last,first,salary,title) values ('Sabochik',' Katelyn A.',62500.00,'DEPUTY DIRECTOR');
insert into Staff(last,first,salary,title) values ('Sahgal',' Rishi R.',66300.00,'DIRECTOR OF WHITE HOUSE PERSONNEL');
insert into Staff(last,first,salary,title) values ('Samuels',' Jonathan D.',130500.00,'SPECIAL ASSISTANT ');
insert into Staff(last,first,salary,title) values ('Sanders',' Trooper',85000.00,'DEPUTY DIRECTOR');
insert into Staff(last,first,salary,title) values ('Santucci',' Laura G.',70000.00,'DEPUTY REGIONAL POLITICAL DIRECTOR');
insert into Staff(last,first,salary,title) values ('Sass',' Joan C.',56791.00,'ASSISTANT SHIFT LEADER');
insert into Staff(last,first,salary,title) values ('Sathe',' Smrthi',70000.00,'ASSOCIATE DIRECTOR');
insert into Staff(last,first,salary,title) values ('Saunders',' George T.',155500.00,'EXECUTIVE CLERK');
insert into Staff(last,first,salary,title) values ('Schafer',' Ellie S.',71400.00,'DIRECTOR OF VISITORS OFFICE');
insert into Staff(last,first,salary,title) values ('Schaub',' Matthew J.',42000.00,'ANALYST');
insert into Staff(last,first,salary,title) values ('Schiliro',' Philip M.',172200.00,'ASSISTANT TO THE PRESIDENT');
insert into Staff(last,first,salary,title) values ('Schmuck',' Robert E.',42000.00,'STAFF ASSISTANT');
insert into Staff(last,first,salary,title) values ('Schuker',' Daniel J. T.',55080.00,'POLICY ADVISOR');
insert into Staff(last,first,salary,title) values ('Schulman',' Kori S.',48450.00,'ASSOCIATE DIRECTOR');
insert into Staff(last,first,salary,title) values ('Schwartz',' Alison K.',75000.00,'WESTERN POLITICAL DIRECTOR');
insert into Staff(last,first,salary,title) values ('Setser',' Bradley W.',110500.00,'DIRECTOR');
insert into Staff(last,first,salary,title) values ('Seymour',' Jennifer D.',107770.00,'POLICY ADVISOR');
insert into Staff(last,first,salary,title) values ('Shah',' Sonal R.',120000.00,'DEPUTY ASSISTANT ');
insert into Staff(last,first,salary,title) values ('Shapiro',' Nicholas S.',78000.00,'ASSISTANT PRESS SECRETARY');
insert into Staff(last,first,salary,title) values ('Shaw',' Katherine',130500.00,'SPECIAL ASSISTANT ');
insert into Staff(last,first,salary,title) values ('Sheehy',' Kristin J.',60000.00,'SPECIAL ASSISTANT ');
insert into Staff(last,first,salary,title) values ('Sher',' Susan S.',172200.00,'ASSISTANT TO THE PRESIDENT');
insert into Staff(last,first,salary,title) values ('Showers',' Wendy W.',84855.00,'PRESIDENTIAL SUPPORT SPECIALIST');
insert into Staff(last,first,salary,title) values ('Sibley',' Sarah E.',50000.00,'SENIOR WRITER');
insert into Staff(last,first,salary,title) values ('Siegel',' Avra C.',50000.00,'SPECIAL ASSISTANT ');
insert into Staff(last,first,salary,title) values ('Simas',' David M.',100000.00,'DIRECTOR OF SPECIAL PROJECTS ');
insert into Staff(last,first,salary,title) values ('Singiser',' Dana E.',130500.00,'SPECIAL ASSISTANT ');
insert into Staff(last,first,salary,title) values ('Sinha',' Manish',42000.00,'OPERATIONS STAFF ASSISTANT');
insert into Staff(last,first,salary,title) values ('Sirbu',' Mara L.',42000.00,'NATIONAL SECURITY STAFF ASSISTANT');
insert into Staff(last,first,salary,title) values ('Skoczek',' Timothy R.',45000.00,'DEPUTY DIRECTOR OF RESPONSE');
insert into Staff(last,first,salary,title) values ('Smith',' Elizabeth S.',130000.00,'DEPUTY ASSISTANT ');
insert into Staff(last,first,salary,title) values ('Smith',' Jason J.',42000.00,'SENIOR ANALYST');
insert into Staff(last,first,salary,title) values ('Smith',' Kelley S.',42000.00,'SENIOR ANALYST');
insert into Staff(last,first,salary,title) values ('Smoot',' Julianna S.',150000.00,'DEPUTY ASSISTANT TO');
insert into Staff(last,first,salary,title) values ('Sobel',' Charlie J.',55000.00,'DIRECTOR OF OPERATIONS');
insert into Staff(last,first,salary,title) values ('Spencer',' Jane C.',76500.00,'MIDWEST POLITICAL DIRECTOR');
insert into Staff(last,first,salary,title) values ('Starkey',' Frances M.',80000.00,'DIRECTOR ');
insert into Staff(last,first,salary,title) values ('Stephens',' Jeffrey M.',75000.00,'DEPUTY DIRECTOR');
insert into Staff(last,first,salary,title) values ('Stephens',' Semonti M.',53550.00,'ASSOCIATE DIRECTOR ');
insert into Staff(last,first,salary,title) values ('Stickel',' Nicole T.',42000.00,'SENIOR ANALYST');
insert into Staff(last,first,salary,title) values ('Stoev',' Ivan',50000.00,'ASSISTANT DIRECTOR');
insert into Staff(last,first,salary,title) values ('Stone',' Wandra E.',112774.00,'SUPERVISOR OF SEARCH AND FILE');
insert into Staff(last,first,salary,title) values ('Stoneman',' Shelly O.',130500.00,'SPECIAL ASSISTANT');
insert into Staff(last,first,salary,title) values ('Stracko',' Jill A.',51000.00,'ASSISTANT DIRECTOR');
insert into Staff(last,first,salary,title) values ('Strautmanis',' Michael A.',139500.00,'SPECIAL ASSISTANT');
insert into Staff(last,first,salary,title) values ('Summers',' Lawrence H.',172200.00,'ASSISTANT ');
insert into Staff(last,first,salary,title) values ('Sutphen',' Mona K.',172200.00,'ASSISTANT ');
insert into Staff(last,first,salary,title) values ('Sutton',' Nikki E.',47500.00,'ASSOCIATE DIRECTOR');
insert into Staff(last,first,salary,title) values ('Swanson',' Gregory C.',42000.00,'SENIOR ANALYST');
insert into Staff(last,first,salary,title) values ('Sweeney',' Sean F.',120000.00,'SPECIAL ASSISTANT');
insert into Staff(last,first,salary,title) values ('Swire',' Peter P.',130500.00,'SPECIAL ASSISTANT');
insert into Staff(last,first,salary,title) values ('Tamarin',' Nathanael P.',96900.00,'ASSOCIATE DIRECTOR');
insert into Staff(last,first,salary,title) values ('Tate-Gilmore',' Ashley R.',45900.00,'ASSOCIATE DIRECTOR AND TRAVEL MANAGER');
insert into Staff(last,first,salary,title) values ('Tchen',' Christina M.',153500.00,'DEPUTY ASSISTANT ');
insert into Staff(last,first,salary,title) values ('Teehee',' Kimberly K.',100000.00,'SENIOR POLICY ADVISOR ');
insert into Staff(last,first,salary,title) values ('Tennison',' Angela N.',42000.00,'STAFF ASSISTANT');
insert into Staff(last,first,salary,title) values ('Terrell',' Louisa M.',130500.00,'SPECIAL ASSISTANT TO THE PRESIDENT');
insert into Staff(last,first,salary,title) values ('Terry',' Joelle L.',65000.00,'DEPUTY DIRECTOR OF MESSAGE EVENTS');
insert into Staff(last,first,salary,title) values ('Thomas',' Maria A.',42000.00,'STAFF ASSISTANT');
insert into Staff(last,first,salary,title) values ('Thorbjornsen',' Lauren K.',45000.00,'EXECUTIVE ASSISTANT');
insert into Staff(last,first,salary,title) values ('Trainor',' Gregory T.',68230.00,'SPECIAL ASSISTANT');
insert into Staff(last,first,salary,title) values ('Tranchin',' Matthew A.',42000.00,'STAFF ASSISTANT');
insert into Staff(last,first,salary,title) values ('Tseggai',' Gannet L.',66300.00,'COMMUNICATIONS ADVISOR');
insert into Staff(last,first,salary,title) values ('Tubman',' Samantha J.',49000.00,'DEPUTY ASSOCIATE DIRECTOR');
insert into Staff(last,first,salary,title) values ('Tucci',' Rosarie G.',51000.00,'SENIOR WRITER');
insert into Staff(last,first,salary,title) values ('Tucker',' Phyllis J.',89033.00,'SUPERVISOR OF COMPUTER ADMINISTRATION');
insert into Staff(last,first,salary,title) values ('Turk',' Andrea E.',50000.00,'DIRECTOR OF INFORMATION SERVICES');
insert into Staff(last,first,salary,title) values ('Turton',' Daniel A.',158500.00,'DEPUTY ASSISTANT TO THE PRESIDENT ');
insert into Staff(last,first,salary,title) values ('Utech',' Daniel G.',130000.00,'ADVISOR');
insert into Staff(last,first,salary,title) values ('Vale',' Elizabeth A.',132009.00,'WHITE HOUSE BUSINESS LIAISON');
insert into Staff(last,first,salary,title) values ('Valencia',' Stephanie M.',61200.00,'DEPUTY ASSOCIATE DIRECTOR');
insert into Staff(last,first,salary,title) values ('Vanderslice',' Mara L.',92001.00,'POLICY ADVISOR');
insert into Staff(last,first,salary,title) values ('Vega',' Dagoberto',100000.00,'SPECIAL ASSISTANT ');
insert into Staff(last,first,salary,title) values ('Verrilli',' Donald B.',158500.00,'DEPUTY ASSISTANT ');
insert into Staff(last,first,salary,title) values ('Vietor',' Thomas F.',78000.00,'ASSISTANT PRESS SECRETARY');
insert into Staff(last,first,salary,title) values ('Vogel',' Matthew A.',71400.00,'ASSOCIATE DIRECTOR');
insert into Staff(last,first,salary,title) values ('Voorman',' David A.',45594.00,'RECORDS MANAGEMENT ANALYST');
insert into Staff(last,first,salary,title) values ('Wade',' David L.',55000.00,'ASSOCIATE DIRECTOR');
insert into Staff(last,first,salary,title) values ('Wade',' Frances J.',44402.00,'RECORDS MANAGEMENT ANALYST');
insert into Staff(last,first,salary,title) values ('Walsh',' Joan L.',60000.00,'ASSISTANT STAFF SECRETARY');
insert into Staff(last,first,salary,title) values ('Wang-Levine',' Adam',55080.00,'POLICY ADVISOR');
insert into Staff(last,first,salary,title) values ('Watkins',' Kyle D. ',45000.00,'SPECIAL ASSISTANT');
insert into Staff(last,first,salary,title) values ('Watson',' Takesha R.',43860.00,'SPECIAL SERVICES OPERATOR');
insert into Staff(last,first,salary,title) values ('Wear',' Michael R.',45900.00,'EXECUTIVE ASSISTANT');
insert into Staff(last,first,salary,title) values ('Webster',' Meridith A.',120000.00,'SPECIAL ASSISTANT');
insert into Staff(last,first,salary,title) values ('Weiser',' Philip J.',172000.00,'SENIOR ADVISOR ');
insert into Staff(last,first,salary,title) values ('White',' Cleo',65393.00,'ANALYST');
insert into Staff(last,first,salary,title) values ('Whitty',' Patrick M.',45000.00,'EXECUTIVE ASSISTANT');
insert into Staff(last,first,salary,title) values ('Williams',' Marie J.',55000.00,'BOARDS  DIRECTOR');
insert into Staff(last,first,salary,title) values ('Williams',' Sherman A.',74958.00,'ASSISTANT');
insert into Staff(last,first,salary,title) values ('Wilson',' Denise R.',130500.00,'SPECIAL ASSISTANT');
insert into Staff(last,first,salary,title) values ('Wilson',' Samuel A.',45000.00,'DEPUTY DIRECTOR');
insert into Staff(last,first,salary,title) values ('Winter',' Melissa',102000.00,'SPECIAL ASSISTANT');
insert into Staff(last,first,salary,title) values ('Witt',' Abigail',45000.00,'SPECIAL ASSISTANT ');
insert into Staff(last,first,salary,title) values ('Wong',' Shale L.',0.00,'POLICY ADVISOR');
insert into Staff(last,first,salary,title) values ('Wright',' Jessica N.',96900.00,'DEPUTY DIRECTOR ');
insert into Staff(last,first,salary,title) values ('Yeager Kaplan',' Jennifer F.',66300.00,'SPECIAL ASSISTANT ');
insert into Staff(last,first,salary,title) values ('Young',' Katherine H.',42000.00,'STAFF ASSISTANT');
insert into Staff(last,first,salary,title) values ('Young',' Latoya A.',58511.00,'RECORDS MANAGEMENT ANALYST');
insert into Staff(last,first,salary,title) values ('Zelman',' Allison L.',50000.00,'POLICY ASSISTANT');
insert into Staff(last,first,salary,title) values ('Zichal',' Heather R.',100000.00,'DEPUTY ASSISTANT ');
